name: eadeploy_cli
description: A CLI-tool version of Easy-Auto-Deploy for manage easily containers
version: 1.0.0-dev
repository: https://github.com/CatHood0/Easy-Auto-Deploy
publish_to: 'none'

environment:
  sdk: ">=3.4.3 <4.0.0" 

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  # for manage container easily
  args: ^2.7.0
  path_provider: ^2.1.5
  dcli: ^8.2.0
  shared_preferences: ^2.5.3
  system_resources: ^1.6.0
  uuid: ^4.5.2
  async: ^2.13.0
  collection: ^1.19.1
  git: ^2.3.2
  meta: ^1.17.0
  # helper to edit/save/parse yaml files
  yaml_edit: ^2.2.2

  # since docker2 had meta pinned to 1.17
  # and path_provider had meta pinned to 1.16
  checked_yaml: ^2.0.4
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  build_runner: ^2.10.3
  json_serializable: ^6.8.0

